LANGUAGES = {
    'af': {'name': 'Afrikaans', 'flag': '🇿🇦'},
    'sq': {'name': 'Albanian', 'flag': '🇦🇱'},
    'am': {'name': 'Amharic', 'flag': '🇪🇹'},
    'ar': {'name': 'Arabic', 'flag': '🇸🇦'},
    'hy': {'name': 'Armenian', 'flag': '🇦🇲'},
    'az': {'name': 'Azerbaijani', 'flag': '🇦🇿'},
    'be': {'name': 'Belarusian', 'flag': '🇧🇾'},
    'bn': {'name': 'Bengali', 'flag': '🇧🇩'},
    'bs': {'name': 'Bosnian', 'flag': '🇧🇦'},
    'bg': {'name': 'Bulgarian', 'flag': '🇧🇬'},
    'ceb': {'name': 'Cebuano', 'flag': '🇵🇭'},
    'ny': {'name': 'Chichewa', 'flag': '🇲🇼'},
    'zh-CN': {'name': 'Chinese (Simplified)', 'flag': '🇨🇳'},
    'zh-TW': {'name': 'Chinese (Traditional)', 'flag': '🇹🇼'},
    'co': {'name': 'Corsican', 'flag': '🇫🇷'},
    'hr': {'name': 'Croatian', 'flag': '🇭🇷'},
    'cs': {'name': 'Czech', 'flag': '🇨🇿'},
    'da': {'name': 'Danish', 'flag': '🇩🇰'},
    'nl': {'name': 'Dutch', 'flag': '🇳🇱'},
    'en': {'name': 'English', 'flag': '🇬🇧'},
    'eo': {'name': 'Esperanto', 'flag': '🌍'},
    'et': {'name': 'Estonian', 'flag': '🇪🇪'},
    'tl': {'name': 'Filipino', 'flag': '🇵🇭'},
    'fi': {'name': 'Finnish', 'flag': '🇫🇮'},
    'fr': {'name': 'French', 'flag': '🇫🇷'},
    'fy': {'name': 'Frisian', 'flag': '🇳🇱'},
    'ka': {'name': 'Georgian', 'flag': '🇬🇪'},
    'de': {'name': 'German', 'flag': '🇩🇪'},
    'el': {'name': 'Greek', 'flag': '🇬🇷'},
    'gu': {'name': 'Gujarati', 'flag': '🇮🇳'},
    'ht': {'name': 'Haitian Creole', 'flag': '🇭🇹'},
    'ha': {'name': 'Hausa', 'flag': '🇳🇬'},
    'haw': {'name': 'Hawaiian', 'flag': '🇺🇸'},
    'iw': {'name': 'Hebrew', 'flag': '🇮🇱'},
    'hi': {'name': 'Hindi', 'flag': '🇮🇳'},
    'hmn': {'name': 'Hmong', 'flag': '🇨🇳'},
    'hu': {'name': 'Hungarian', 'flag': '🇭🇺'},
    'is': {'name': 'Icelandic', 'flag': '🇮🇸'},
    'ig': {'name': 'Igbo', 'flag': '🇳🇬'},
    'id': {'name': 'Indonesian', 'flag': '🇮🇩'},
    'ga': {'name': 'Irish', 'flag': '🇮🇪'},
    'it': {'name': 'Italian', 'flag': '🇮🇹'},
    'ja': {'name': 'Japanese', 'flag': '🇯🇵'},
    'jw': {'name': 'Javanese', 'flag': '🇮🇩'},
    'kn': {'name': 'Kannada', 'flag': '🇮🇳'},
    'kk': {'name': 'Kazakh', 'flag': '🇰🇿'},
    'km': {'name': 'Khmer', 'flag': '🇰🇭'},
    'ko': {'name': 'Korean', 'flag': '🇰🇷'},
    'ky': {'name': 'Kyrgyz', 'flag': '🇰🇬'},
    'lo': {'name': 'Lao', 'flag': '🇱🇦'},
    'la': {'name': 'Latin', 'flag': '🏛️'},
    'lv': {'name': 'Latvian', 'flag': '🇱🇻'},
    'lt': {'name': 'Lithuanian', 'flag': '🇱🇹'},
    'lb': {'name': 'Luxembourgish', 'flag': '🇱🇺'},
    'mk': {'name': 'Macedonian', 'flag': '🇲🇰'},
    'mg': {'name': 'Malagasy', 'flag': '🇲🇬'},
    'ms': {'name': 'Malay', 'flag': '🇲🇾'},
    'ml': {'name': 'Malayalam', 'flag': '🇮🇳'},
    'mt': {'name': 'Maltese', 'flag': '🇲🇹'},
    'mi': {'name': 'Maori', 'flag': '🇳🇿'},
    'mr': {'name': 'Marathi', 'flag': '🇮🇳'},
    'mn': {'name': 'Mongolian', 'flag': '🇲🇳'},
    'my': {'name': 'Myanmar (Burmese)', 'flag': '🇲🇲'},
    'ne': {'name': 'Nepali', 'flag': '🇳🇵'},
    'no': {'name': 'Norwegian', 'flag': '🇳🇴'},
    'ps': {'name': 'Pashto', 'flag': '🇦🇫'},
    'fa': {'name': 'Persian', 'flag': '🇮🇷'},
    'pl': {'name': 'Polish', 'flag': '🇵🇱'},
    'pt': {'name': 'Portuguese', 'flag': '🇵🇹'},
    'pa': {'name': 'Punjabi', 'flag': '🇮🇳'},
    'ro': {'name': 'Romanian', 'flag': '🇷🇴'},
    'ru': {'name': 'Russian', 'flag': '🇷🇺'},
    'sm': {'name': 'Samoan', 'flag': '🇼🇸'},
    'gd': {'name': 'Scots Gaelic', 'flag': '🏴󠁧󠁢󠁳󠁣󠁴󠁿'},
    'sr': {'name': 'Serbian', 'flag': '🇷🇸'},
    'st': {'name': 'Sesotho', 'flag': '🇱🇸'},
    'sn': {'name': 'Shona', 'flag': '🇿🇼'},
    'sd': {'name': 'Sindhi', 'flag': '🇵🇰'},
    'si': {'name': 'Sinhala', 'flag': '🇱🇰'},
    'sk': {'name': 'Slovak', 'flag': '🇸🇰'},
    'sl': {'name': 'Slovenian', 'flag': '🇸🇮'},
    'so': {'name': 'Somali', 'flag': '🇸🇴'},
    'es': {'name': 'Spanish', 'flag': '🇪🇸'},
    'su': {'name': 'Sundanese', 'flag': '🇮🇩'},
    'sw': {'name': 'Swahili', 'flag': '🇹🇿'},
    'sv': {'name': 'Swedish', 'flag': '🇸🇪'},
    'tg': {'name': 'Tajik', 'flag': '🇹🇯'},
    'ta': {'name': 'Tamil', 'flag': '🇮🇳'},
    'te': {'name': 'Telugu', 'flag': '🇮🇳'},
    'th': {'name': 'Thai', 'flag': '🇹🇭'},
    'tr': {'name': 'Turkish', 'flag': '🇹🇷'},
    'uk': {'name': 'Ukrainian', 'flag': '🇺🇦'},
    'ur': {'name': 'Urdu', 'flag': '🇵🇰'},
    'uz': {'name': 'Uzbek', 'flag': '🇺🇿'},
    'vi': {'name': 'Vietnamese', 'flag': '🇻🇳'},
    'cy': {'name': 'Welsh', 'flag': '🏴󠁧󠁢󠁷󠁬󠁳󠁿'},
    'xh': {'name': 'Xhosa', 'flag': '🇿🇦'},
    'yo': {'name': 'Yoruba', 'flag': '🇳🇬'},
    'zu': {'name': 'Zulu', 'flag': '🇿🇦'}
}


def get_language_name(lang_code):
    return LANGUAGES.get(lang_code, {}).get('name', lang_code)


def get_flag_emoji(lang_code):
    return LANGUAGES.get(lang_code, {}).get('flag', '🌐')


def get_all_languages():
    return LANGUAGES
